Rename "Window" to "Range" where appropriate
vais-ral/CILViewer pull request #268
Opened 2022-06-20 17:47 UTC by lauramurgatroyd

closes #267

2022-06-20 17:48 UTC, lauramurgatroyd commented
I only thought of this afterwards but if you prefer we could use "Limits" instead of "Range" ?

2022-06-21 09:18 UTC, Pasarus requested changes
A few comments before I look into the code functionality

2022-06-21 09:18 UTC, Pasarus commented on Wrappers/Python/ccpi/web_viewer/dev-environment.yml
> +name: cilviewer_webapp_trame2
I don't like this renaming it adds unnecessary length to the name that you'd have to type.

2022-06-21 09:18 UTC, Pasarus commented on Wrappers/Python/ccpi/web_viewer/dev-environment.yml
> +  - trame  # pin version for pip
Should be handled in the other PR https://github.com/vais-ral/CILViewer/pull/262

2022-06-21 09:29 UTC, lauramurgatroyd commented
Sorry Sam I didn't mean to push my changes to the environment file! They were from when i was trying to get trame2 working!

2022-06-21 09:31 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/web_viewer/dev-environment.yml
> +name: cilviewer_webapp_trame2
```suggestion
name: cilviewer_webapp
```

2022-06-21 09:31 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/web_viewer/dev-environment.yml
> +  - trame  # pin version for pip
```suggestion
  - trame<2.0  # pin version for pip
```

2022-06-21 10:25 UTC, merged