Refactor to reduce complication
vais-ral/CILViewer pull request #269
Opened 2022-06-21 12:27 UTC by Pasarus

An easy refactor to review, just code changes.

2022-06-21 15:37 UTC, lauramurgatroyd requested changes
One small suggestion. Otherwise, I don't mind the changes although I am in the middle of making a PR which reverts a lot of them because I am making it so that the 2D and 3D viewers have the same named methods for changing the slice's window and level.

BTW I didn't check it still runs, but I assume you did.

2022-06-21 15:37 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/web_viewer/trame_viewer.py
> -        self.html_view.update()
you could still leave these here, then the 2D viewer would use the parent's change_slice_number unmodified, and the 3D viewer could run self.cil_viewer.updateSliceHistogram() and then call change_slice_number from the parent

2022-06-21 15:38 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/web_viewer/trame_viewer3D.py
> +        self.html_view.update()
why is this percentage stuff a thing only in the 3D case?

2022-06-21 15:43 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/web_viewer/trame_viewer3D.py
> +        self.html_view.update()
Oh I think the percentiles method only exists in the 3D viewer currently? So another thing for me to update

2022-06-22 12:22 UTC, Pasarus commented
Waiting to take stock in whether this is required anymore after this PR is finished/merged: https://github.com/vais-ral/CILViewer/pull/270

2022-06-23 14:27 UTC, Pasarus commented
This work will be replicated on top of #270 as part of work to create tests for the web app.

2022-06-23 14:27 UTC, closed without merging