Tiff cropped reader
vais-ral/CILViewer pull request #271
Opened 2022-06-22 21:27 UTC by paskino

Added TIFF Cropped Reader and unit tests.

closes #126

2022-06-24 20:52 UTC, paskino commented on Wrappers/Python/ccpi/viewer/utils/conversion.py
> +        return self._TargetExtent
Agreed, but should be made available later

2022-06-27 10:22 UTC, lauramurgatroyd requested changes
Looks good, just some suggestions for docstrings and removing some unused lines

2022-06-27 10:22 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/viewer/utils/conversion.py
> +class vortexTIFFCroppedReader(cilBaseCroppedReader, vortexTIFFImageReaderInterface):
shall we leave as cil rather than vortex?

2022-06-27 10:22 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/viewer/utils/conversion.py
> +    image = reader.GetOutput()
```suggestion
    This example reads from a list of tiff filenames = tiff_fnames
    and crops it on the z axis to extent (1, 3):

    reader = vortexTIFFCroppedReader()
    reader.SetFileName(tiff_fnames)
    reader.SetTargetZExtent([1,3])
    reader.Update()
    image = reader.GetOutput()
```

Docstring needs updating to something like this.

2022-06-27 10:22 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/viewer/utils/conversion.py
> +        tmpdir = tempfile.mkdtemp()
```suggestion
```
tmpdir not used

2022-06-27 10:22 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/viewer/utils/conversion.py
> +        big_endian = self.GetBigEndian()
```suggestion
```

2022-06-27 10:22 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/viewer/utils/conversion.py
> +        file_header_length = self.GetFileHeaderLength()
```suggestion
```

2022-06-27 20:56 UTC, paskino commented on Wrappers/Python/ccpi/viewer/utils/conversion.py
> +        file_header_length = self.GetFileHeaderLength()
removed

2022-06-28 08:13 UTC, lauramurgatroyd approved these changes

2022-06-28 09:28 UTC, merged