Viewer toolbar
vais-ral/CILViewer pull request #337
Opened 2023-02-20 09:26 UTC by Dagonite

Implementation of the viewer GUI toolbar.

2023-02-20 09:34 UTC, lauramurgatroyd commented
Hi @Dagonite, thanks for opening the PR! We have a training course/hackathon coming up soon for our CIL software, so we are pretty busy over the next few weeks. This means we probably won't get on to looking at this yet, but we will get back to it after then!

2023-03-31 15:41 UTC, lauramurgatroyd requested changes
Unfortunately we cannot yet use imports from vtkmodules as we still have to support vtk8 for the iDVC app.

Instead we need to use: colors = vtk.vtkNamedColors()

This requires some more changes rather than just the import change so I will look into this another time

2023-03-31 15:41 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/viewer/ui/SettingsDialog.py
> +from vtkmodules.util import colors
```suggestion
from vtk import vtkNamedColors as colors
```

2023-03-31 15:41 UTC, lauramurgatroyd commented on Wrappers/Python/ccpi/viewer/ui/helpers.py
> +from vtkmodules.util import colors
```suggestion
from vtk import vtkNamedColors as colors
```

2023-06-16 21:10 UTC, paskino commented
Relevant changes are updated in #347

2023-06-16 21:10 UTC, closed without merging